swagger: "2.0"
info:
  title: "Enteco API Oracle"
  version: "1.0"
paths:
  /enteco/api-ora/observaciones-cliente/requerido-vacios/{empresa_id}/{cliente_id}:
    get:
      responses:
        200:
          description: "OK"
